### ISSUE TITLE
leading repo naming/structure

### ISSUE THREAD

**Issue by hzierer** [eclipse-tractusx/vas-country-risk#15]
According to [TRG2.04](https://eclipse-tractusx.github.io/docs/release/trg-2/trg-2-4) the leading repository shall be named with no suffix (like this one with -frontend).

hint: will become relevant for QG5

**Comment by fabiodmota** [comment]
Hello @hzierer as you mentioned i asked for the rename on the leading repo 
https://github.com/eclipse-tractusx/vas-country-risk

**Comment by fabiodmota** [comment]
Hi @hzierer can we close this one ?

**Comment by hzierer** [comment]
sure. sorry missed the notification
