### ISSUE TITLE
TRG 1.04 editable static files

### ISSUE THREAD

**Issue by FaGru3n** [eclipse-tractusx/vas-country-risk#91]
Hi all, found some various screenshots and also some sequence diagramms within `.png` format that could have to be editable like described in https://eclipse-tractusx.github.io/docs/release/trg-1/trg-1-4/

so i would suggest file like a 

> All diagram files must be either using code to generate diagrams, or stored as .svg file within our repositories
> 
> This includes:
> diagrams
> flowcharts
> sequence diagrams
> state diagrams
> gantt charts
> etc.
>

**Comment by fabiodmota** [comment]
Hi Fabian , most of our images png and svg files were done to document first guidelines , all new images since the TRG are on mermaid or other tools that can be editable

**Comment by FaGru3n** [comment]
Hi @fabiodmota ,

sure no problem for the "userguide-pics.png" it is more related to your diagram files.

same examples that are diagramms and as stated in our TRG:
> All diagram files must be either using code to generate diagrams, or stored as .svg file within our repositories.

some examples:

- https://github.com/eclipse-tractusx/vas-country-risk/blob/country-risk-3.0.9/docs/Images/DashBoardResource_getAllDashBoardTable.jpg
- https://github.com/eclipse-tractusx/vas-country-risk/blob/country-risk-3.0.9/docs/Images/DashBoardResource_getCountrys.jpg
- https://github.com/eclipse-tractusx/vas-country-risk/blob/country-risk-3.0.9/docs/Images/DataModel_v6.png
- https://github.com/eclipse-tractusx/vas-country-risk/blob/country-risk-3.0.9/docs/Images/StandardisedDataExchange.png
- #https://github.com/eclipse-tractusx/vas-country-risk/blob/country-risk-3.0.9/docs/Images/diagram_compenent.png

so easiest way would be rechecking on diagram files and storve it as .svg but better would be dedicates `.puml` or `.mmd / .mermaid` files

**Comment by FaGru3n** [comment]
Found also some sequence diagramms that could be easily adopted with mermaid

for example and all other "DashBoardRessource_xxxxx" could also be modified.
https://github.com/eclipse-tractusx/vas-country-risk/blob/main/docs/Images/DashBoardResource_getAllDashBoardTable.jpg

**Comment by FaGru3n** [comment]
For our current state i would check this item in the QG-Checks Tasklist, because now i think you get the point to update your diagrams into editable files and will leave this issue open if you have further questions and feedback how to update you "editable diagram files" 😉
